FORMAT: 1A

# Module Account
REST API for Account module. This module contains everything for logging, security and account management used for services.


## POST /account/login

+ Request (application/json)

    + Body
    
            {
                "userLoggin": {
                    "userName": "{user_name}",
                    "password": "{password}"
                }
            }

+ Response 200 (application/json)

    + Headers

            X-HFB-SID: {sid}
            
    + Body

            {
                "userLoggin": {
                    "userName": "{user_name}"
                }
            }

## POST /account/logout

+ Request

    + Headers

            X-HFB-SID: {sid}
            
+ Response 200

## GET /account/info

+ Request (application/json)

    + Headers

            X-HFB-SID: {sid}
            
    + Body
    
            {
                "userLoggin": {
                    "userName": "{user_name}",
                    "password": "{password}"
                }
            }

+ Response 200 (application/json)

    + Body

            {
                "userLoggin": {
                    "userName": "{user_name}"
                }
            }
